// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using noofs.SWRules.EntityFrameworkCore;

namespace noofs.SWRules.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(SWRulesDbContext))]
    [Migration("20180702185309_MoveTo_AspBoilerplate")]
    partial class MoveTo_AspBoilerplate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("noofs.SWRules.Rules.Power", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Book");

                    b.Property<DateTime>("CreationTime");

                    b.Property<long?>("CreatorUserId");

                    b.Property<long?>("DeleterUserId");

                    b.Property<DateTime?>("DeletionTime");

                    b.Property<string>("Distance");

                    b.Property<string>("Duration");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<long?>("LastModifierUserId");

                    b.Property<string>("Name");

                    b.Property<string>("Points");

                    b.Property<string>("Rank");

                    b.Property<string>("Text");

                    b.Property<string>("Trappings");

                    b.HasKey("Id");

                    b.ToTable("Powers");
                });
#pragma warning restore 612, 618
        }
    }
}
